a=input("ENTER YOUR NAME::")
b=input("ENTER YOUR LAST NAME::")
c=int(input("ENTER YOUR AGE::"))
d=int(input("ENTER YOUR FAVOURATE NUMBER 1::"))
e=int(input("ENTER YOUR FAVOURATE NUMBER 2::"))
f=a.upper()
print(a.center(30,"~"))
print(f)
print("\ncurrent age:: ",c)
print("age after 5 yiears",c+5)
print("your favourates number  " ,d ,"and", e)
print("addition",d+e)
print("multification",d*e)
print("cool ! nice ",a.upper().center(30,'$'))
print("EXCUTED SUCCESSFULLY" .center(30,'~'))